### ISSUE TITLE
About Response Header Settings

### ISSUE THREAD

**Issue by KTetsuyuki** [abeyad/user-agent-reduction#9] opened 2022-04-06 10:30 UTC
How do I set up a 「User-Agent reduction deprecation trial」?

The following settings were made in the response header

accept-ch: Sec-CH-UA-Mobile,Sec-CH-UA-Platform,Sec-CH-UA-Arch,Sec-CH-UA-Bitness,Sec-CH-UA-Arch,Sec-CH-UA-Model,Sec-CH-UA-Platform-Version,Sec-CH-UA-Full-Version-List,Sec-CH-UA-WoW64,Sec-CH-UA-Full
critical-ch: Sec-CH-UA-Full
origin-trial: ＜ORIGIN TRIAL TOKEN＞

However, the following values were missing from the request header

sec-ch-ua-full: ?1

The user agent also did not have the expected value, as shown below.

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.0 Safari/537.36

What is the cause?
Should only Sec-CH-UA-Full be set for accept-ch?

**Comment by abeyad** [comment] 2022-04-06 19:25
Hi, thanks for your question!

What was the origin/URL for which you didn't observe sec-ch-ua-full in the request headers?

Your response headers look correct.

In the UA string value, you mentioned the version as:
```
Chrome/100.0.0
```

However, that seems to be missing a digit (there should be four components e.g. 100.0.4823.23).

**Comment by miketaylr** [comment] 2022-04-06 21:13
Also curious if you might have accidentally set chrome://flags/#reduce-user-agent? Otherwise you shouldn't see "100.0.0.0" (assuming that missing 0 isn't a typo)

**Comment by KTetsuyuki** [comment] 2022-04-07 01:28
Thank you for your response.

Chrome/100.0.0 is a typo.

Sorry, I cannot tell you about the URL.

I have the "chrome://flags/#reduce-user-agent" setting. Does the "chrome://flags/#reduce-user-agent" setting disable the "User-Agent reduction deprecation trial" setting?

If so Is there any way to verify that the "User-Agent reduction deprecation trial" is working correctly until "UA Strings Phase 4" begins?

**Comment by abeyad** [comment] 2022-04-07 03:42
Yes, setting chrome://flags/#reduce-user-agent overrides any UA string settings, including what's triggered by an origin trial.

If you want to verify via your browser that the deprecation trial is working, you can just disable the chrome://flags/#reduce-user-agent flag and try visiting your site again.

**Comment by KTetsuyuki** [comment] 2022-04-08 01:35
I turned off "chrome://flags/#reduce-user-agent".

However, I checked the request header.

```
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="100", "Google Chrome";v="100"
sec-ch-ua-arch: "x86"
sec-ch-ua-bitness: "64"
sec-ch-ua-full-version-list: " Not A;Brand";v="99.0.0.0", "Chromium";v="100.0.4896.75", "Google Chrome";v="100.0.4896.75"
sec-ch-ua-mobile: ?0
sec-ch-ua-model: ""
sec-ch-ua-platform: "Windows"
sec-ch-ua-platform-version: "8.0.0"
sec-ch-ua-wow64: ?0
sec-fetch-dest: document
sec-fetch-mode: navigate
sec-fetch-site: none
sec-fetch-user: ?1
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36
```

There was no "sec-ch-ua-full : ?1".

I set `"Origin-Trial", "Accept-CH", and "Critical-CH"` to the test environment to check.
This test environment is the same URL as the production environment.
The test environment can be viewed by changing "hosts" (adding IP addresses).

In the above case, is it possible to check "User-Agent reduction deprecation trial"?

**Comment by miketaylr** [comment] 2022-04-08 14:23
Could you share a screenshot of the response headers?

**Comment by abeyad** [comment] 2022-04-08 14:26
@KTetsuyuki are there any redirects happening in your chain of requests?

**Comment by KTetsuyuki** [comment] 2022-04-11 07:07
An image of the response header is attached.
The status in the response header is "200" as shown in the image.
However, since Akamai's service is used, there may be a redirection process.

Does the "User-Agent reduction deprecation trial" not work correctly when there is a redirection process?
Are there any other possible causes?

Thank you in advance for your help and guidance.

![001](https://user-images.githubusercontent.com/101867799/162681330-68337031-4c3f-48de-976e-69bd2f0e4e01.png)
![002](https://user-images.githubusercontent.com/101867799/162681333-7782d0b3-5bc4-4c86-8697-80d6a05c0df6.png)
![003](https://user-images.githubusercontent.com/101867799/162681335-81f1586b-eb85-4231-9d71-f00e3220e6f1.png)

**Comment by miketaylr** [comment] 2022-04-11 13:19
Thanks @KTetsuyuki. Could you describe the flow for the site and how it interacts with the Akamai service?

e.g., `example.com => 302 to akamai.com 302 to => example2.com`?

**Comment by KTetsuyuki** [comment] 2022-04-12 01:50
The image of the interaction with Akamai is as shown in the image.

When a user accesses "example.com," if the Akamai Edge server has a cache of the content, it returns a response to the user.

If there is no cache, a request is made to the origin server to provide the content.

Sorry, I don't know if the status code is 200 or 302 between Akamai and origin server.
![004](https://user-images.githubusercontent.com/101867799/162862139-26a11428-0fb4-4fab-b353-897fa263db8e.png)

**Comment by abeyad** [comment] 2022-04-12 14:21
Those don't seem to be redirects - all the redirection is happening server-side to deliver the content from the right place.

(1) Is this a top-level request or a subresource request or iframe?
(2) I'm wondering if your Origin-Trial token is registered for the wrong origin.  Can you visit https://googlechrome.github.io/OriginTrials/check-token.html and validate whether your token is correct?

**Comment by KTetsuyuki** [comment] 2022-04-19 00:59
This is not an  iframe or  subresource request.
It is a top-level request.

I checked about tokens. There appears to be no problem.

I had applied for a token for the origin trial with reference to "https://github.com/GoogleChrome/OriginTrials/blob/gh-pages/developer-guide.md#valid-until-feedback".

For example, if you have a domain like
"www.a.in.example.go.jp"
"www.b.in.example.go.jp"
"www.c.in.example.go.jp"

We recognize that an application at "https://example.go.jp" would cover all of the above domains.
Is this perception incorrect?

**Comment by abeyad** [comment] 2022-04-19 15:32
Your example is correct, it essentially does a suffix match[1][2]. 

Is your domain that you registered the token for in the Public Suffix List?  https://publicsuffix.org/list/public_suffix_list.dat
If so, that wouldn't work (though I believe the origin trial registration page would give you an error if that was the case).

You can also look at the demo site we have up on glitch (including the source code) to see if there's anything you might be doing different?  https://uard-ot-demo.glitch.me/

[1] https://github.com/GoogleChrome/OriginTrials/blob/gh-pages/developer-guide.md#13-i-have-multiple-testingstaging-domains-or-subdomains-that-are-programmatically-generated-do-i-need-to-request-a-token-for-every-subdomain.
[2] This is the function that's called in chromium to do the matching, if you're interested: https://source.chromium.org/chromium/chromium/src/+/main:url/url_util.h;l=196;drc=c4b56465e4821b2a357367c76e72bc96b8acb65a

**Comment by iwanoori** [comment] 2022-06-17 05:31
Hi abeyad,

I'm on the same team that Tetsuyuki was on.
We have set up an origin trial on the site, but it is not working.
We couldn't get  'sec-ch-ua-full: ?1' or full text user agent string.
We've checked our token and it's valid.
![image](https://user-images.githubusercontent.com/107548278/174230513-e5c8e450-768d-4591-baa2-17747e494e88.png)

We also checked the demo site "https://uard-ot-demo.glitch.me/" to see how it works, but it's not what we expected.
I thought that "Subsequent Request User-Agent" would be full user agent string, but it was reduced one. 
Is this behavior correct ?
![image](https://user-images.githubusercontent.com/107548278/174231473-20079f74-6030-405e-a174-c453b91b1e98.png)


Is there anything we can try to solve this?

**Comment by miketaylr** [comment] 2022-06-17 17:36
Thanks for the ping @iwanoori - we're looking into this, and will leave an update once we have some more info.

**Comment by miketaylr** [comment] 2022-06-23 15:52
We've got a fix landed in Canary - feel free to verify. Looking to get it merged back as far as is reasonable: https://bugs.chromium.org/p/chromium/issues/detail?id=1338959

**Comment by iwanoori** [comment] 2022-06-28 09:31
Using the Canary version, we actually verified the operation on our site, but did not get the results we wanted.
Therefore, we issued three new types of tokens and checked them.

Tested sites
　A:www.hoge-hoge.example.com
　B:www.example.com

Verification tokens
 Token1(Subdomain:No,third party:No,orgin:https:/www.example.com:443) 
 Token2(Subdomain:No,third party:No,orgin:https:/www.hoge-hoge.example.com:443) 
 Token3(Subdomain:Yes,third party:No,orgin:https:/www.example.com:443)
 Token4(Subdomain:No,third party:Yes,orgin:https:/www.example.com:443)

As a result
Token3 and Token4 did not work at all and did not return "Sec-CH-UA-Full: ?1".
Token3 was set and checked at both Site A and Site B, but did not work at either site.

Token1 and Token2 worked.
However, the deprecated trial did not work well on the first access immediately after clearing the browser cache.
After that, it worked correctly when the page was reloarded or jumped to another page within the site.
The same behavior was observed in the developer tool of the demo site.

● the first time of clicking "Send"  immediately after clearing the browser cache.
![image](https://user-images.githubusercontent.com/107548278/176145232-29390ace-9927-4752-b706-5485bcf87fc7.png)


Anyway, we only want to use Token3 .
The purpose of this verification was to see if it works for different tokens with the same configuration method.
In our configuration it did not work except Token1 and Token2. Is there any difference in the configuration method between Token3 and Token2?
Are there any possible flaws in the way tokens are issued?

**Comment by miketaylr** [comment] 2022-06-28 12:43
> However, the deprecated trial did not work well on the first access immediately after clearing the browser cache.
> After that, it worked correctly when the page was reloarded or jumped to another page within the site.

This is expected behavior. See step 2 of https://developer.chrome.com/blog/user-agent-reduction-deprecation-trial/#setup, and in particular step 3. Are you including `Critical-CH` w/ the `Sec-CH-UA-Full` token?

Adding @Tanych for the question on the OT token setups.

**Comment by Tanych** [comment] 2022-06-28 19:08
yea, please double check your Accept-CH / Critical-CH setting and permission-policy setting for third party subresource request.

**Comment by iwanoori** [comment] 2022-06-30 06:05
**(1) The behavior of the first navigation request**.
We have confirmed in the server-side logs that the behavior is as described on the site (https://developer.chrome.com/blog/user-agent-reduction-deprecation-trial/#setup). Therefore, this matter has been resolved. Thank you very much.

**(2) About tokens in subdomains**.
The deprecated trial did not work with tokens with subdomains. We confirmed this by changing only the tokens on the same site. All were with `Critical-CH` set. When tokens with subdomains were set, "`Sec-CH-UA-Full`: ?1" was never returned.
It was the same with and without `Critical-CH`.
Please check the behavior with tokens with subdomains.
![image](https://user-images.githubusercontent.com/107548278/176601185-d04d0abf-5efd-4d6e-8765-99accd6faba5.png)

**(3) Permission policy settings for third-party sub-resource requests**.
A third-party sub-resource request is a request sent to a third party to retrieve information for embedding in a page, correct? For example, a request to Facebook to get Embedded Posts, a request to Google to retrieve map information, etc. We do not want to send a full ua string in such a request. As far as using Token1 to Token3 above, I am assuming that what will be sent to the third party will be a reduced ua string, is that correct?

**Comment by Tanych** [comment] 2022-06-30 13:39
Here are some information might be helpful:

### Third-party 
Origin trial for third-party means that third party embeds (for example, an iframe inside another site) can participate in the origin trial without requiring the top-level site to be enrolled.  For example:

`mysite.com `embeds `example.com`

```
<iframe src="https://example.com/index.html"></iframe>
```
if `example.com` participates in the UA reduction deprecation origin trial,  when user visiting `example.com` from `mysite.com`, `example.com` will have full UA string.

The UA reduction deprecation origin trial is similar with the UA reduction origin trial. For detail, you can check https://developer.chrome.com/blog/user-agent-reduction-origin-trial/#enroll-third-party

### subdomains

~~If I remember correctly, we don't support subdomains for UA deprecation origin trial, but I will double check.~~

After double checking, we do support subdomain, and the code works expected when adding your example (probably we haven't enable the subdomain option for UA reduction deprecation in the origin trial site). 

* origin: https://www.sample.com:443, test_url: https://www.sample.com/index.html

for the second example, it doesn't work because `https://www.hoge-hoge.sample.com` seems not a subdomain of `https://www.sample.com`

I will try to verify in the demo site as well.

**Comment by iwanoori** [comment] 2022-07-06 09:06
Thank you all.
I changed the origin from "https://www.sample.com" to "https://sample.com" and it worked fine.

One last question.
Is it correct that the bug fix for deprecation original trial(Issue [1338959](https://bugs.chromium.org/p/chromium/issues/detail?id=1338959)) will be released in Chrome 104?

**Comment by Tanych** [comment] 2022-07-06 14:16
no problem, that's true, it will release in Chrome M104.

**Comment by iwanoori** [comment] 2022-10-27 06:48
Hi guys,
I'd like to compare the UserAgent strings sent to sites with and without reverse origin trials to confirm that reverse origin trials are also valid for Phase 5 of UserAgent reduction.
I have a Windows 11 PC for this purpose, but the UserAgent string for Windows 11 is set to Windows 10 from the start.

Is there any way to check this?

**Comment by miketaylr** [comment] 2022-10-27 22:53
Hi @iwanoori - on a Windows 11 PC, it will be difficult to see the difference, unless you install a 32 bit Chrome on Windows 64. If that's the case, on the "unreduced UA", you should expect to see the "WOW64" token in the UA string, similar to `Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36`.

(I don't really know how to install 32bit Chrome on Windows, but https://www.digitalcitizen.life/how-download-install-64-bit-version-google-chrome/#ftoc-heading-2 has some instructions that _might_ work)

**Comment by miketaylr** [comment] 2022-10-27 22:55
> Hi guys, I'd like to compare the UserAgent strings sent to sites with and without reverse origin trials to confirm that reverse origin trials are also valid for Phase 5 of UserAgent reduction. I have a Windows 11 PC for this purpose, but the UserAgent string for Windows 11 is set to Windows 10 from the start.
> 
> Is there any way to check this?

I missed that you said "reverse origin trial" - so the simplest way to test will be to look at the version number. If it reports something like `106.0.0.0`, it is not working. But if it reports something like `106.0.5249.119 `, then it is working.

**Comment by Tanych** [comment] 2022-10-28 01:02
@iwanoori do you mean how to compare the OS CPU information (phase 5 user-agent reduction) between the reduced user-agent and the full user-agent?

On a Windows 11 PC, it's difficult to see the difference, the OS CPU in the user agent might be the same for reduced user-agent and full user-agent, they both look like  `Windows NT 10.0` since windows 11 os major version is also  `10`. https://learn.microsoft.com/en-us/windows/win32/sysinfo/operating-system-version

If you have a legacy Windows PC like win7 or win 8, you can see the difference for phase 5 user-agent reduction once you are with and without the user-agent deprecation origin trial.

* with the user-agent deprecation origin trial: 

```
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.5383.4 Safari/537.36
```

* without: 

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

```

**Comment by iwanoori** [comment] 2022-11-09 10:20
Thanks a lot.

We tried to see if the reverse-origin trial worked with Phase 5 user-agent reduction. It would have been best if the OS CPU in user-agent string were different, but that seems to be difficult. I can't provide a legacy Windows PC, so I gave up on that. 
Anyway, I see the full browser version in user agent string, so I could test if the reverse origin trial is working.
Thank you for information. My probrem has been solved.


For your information, I also checked with 32 bit Chrome, but there was no difference in OS-related information between with and without the reverse origin trial. The results are as follows
- Site with reverse origin trial: 
`Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.5304.106 Safari/537.36`

- Site without reverse origin trial:
`Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0. Safari/537.36`

**Comment by miketaylr** [comment] 2022-11-10 00:56
Glad to hear @iwanoori. Let's close here, feel free to open a new issue for other questions.

**Closed as completed by miketaylr** 2022-11-10 00:56 UTC

**Comment by iwanoori** [comment] 2023-04-12 03:29
Hi guys,

Let me check just to be sure, there is no problem viewing a site with the reverse origin trial token on Chrome 113, right?
Chrome 113 (User-Agent Reduction Completion Phase 7) will be released on April 26th and I'm planning to remove the reverse origin trial token from our websites in May.

**Comment by miketaylr** [comment] 2023-04-12 19:33
Correct - no issue. Even if it's expired, nothing bad will happen. :)
